### ISSUE TITLE
Add support for accessing Job configuration in Workflows

### ISSUE THREAD

**Issue by icj217** [cdklabs/cdk-pipelines-github#170]
I'm trying to create a CI pipeline that synths/runs some tests against a CDK application, but I don't want the pipeline to run on forks of the repository. Github gives you a way to control this via the `if` property that you set at the `Job` level, but there doesn't seem to be a way to get at this property via the `GithubWorkflow` construct or any of the internals ([here's where I'm looking](https://github.com/cdklabs/cdk-pipelines-github/blob/9179bff4bb37ac8176ab09d811c8a389ba329ef4/src/pipeline.ts#L465))

It would be nice if the resulting `GithubWorkflow` instance exposed the various `Job`'s it is composed of, so that we can customize them appropriately.

I did try adding `if_='github.organization == "my_org"'` to all my `JobStep`s but that doesn't get at the steps that the construct handles in the background (e.g. synth, artifact creation, etc)

```python
import cdk_pipelines_github as GithubPipelines

# Pipeline that only does CI for now
pipeline = GithubPipelines.GitHubWorkflow(app, 'GithubPipeline',
    workflow_name="CI",
    workflow_path=".github/workflows/ci.yml",
    pre_build_steps=[
        GithubPipelines.JobStep(name="Initialize", run="make venv"),
        GithubPipelines.JobStep(name="Run tests", run="make test")
    ],
    synth=Pipelines.ShellStep('Build', commands=["make synth"]),
    post_build_steps=[
        GithubPipelines.JobStep(name="Check output", run="ls -al"),
        GithubPipelines.JobStep(name="Check cdk output", run="ls -al cdk.out/")
    ],
    workflow_triggers=GithubPipelines.WorkflowTriggers(
        push=GithubPipelines.PushOptions(branches=["main"]),
        pull_request=GithubPipelines.PullRequestOptions()
    ))
```

**Comment by kaizen3031593** [comment]
Great! Thanks for letting me know your use case and what you'd like to see. My intuition is that you'd want to constrain all your jobs this way or none of them, so this should be exposed as a property on the `GitHubWorkflow` itself (not on the `Job` granularity.

 I'm wary of exposing the internal jobs of the `GitHubWorkflow` because that's a pandoras box. Some things we should keep internal and not let users mess with them :).

Let me know if you think something like this would work for you:

```python
pipeline = GithubPipelines.GitHubWorkflow(app, "GithubPipeline",
  worfklow_name="CI",
  job_settings= GithubPipelines.JobSettings("if", "github.organization == 'my_org'"), # i haven't thought through the API but it would be set here
)
```

**Comment by icj217** [comment]
Thanks for the quick response @kaizen3031593 !

> I'm wary of exposing the internal jobs of the `GitHubWorkflow` because that's a pandoras box. Some things we should keep internal and not let users mess with them :).

Understandable, though I think that users of the construct would appreciate the flexibility of being able to make "out-of-bound" changes to the workflow template that aren't exposed as first-party constructs, especially since (to my knowledge) that is possible with the CDK Pipelines library since it compiles down to CFN and you can use casting/escape hatches to mutate as necessary while keeping those changes as part of the CDK code (and thus the CDK code being the "authoritative" source of truth of how the pipeline looks).

> 
> Let me know if you think something like this would work for you:
> 
> ```python
> pipeline = GithubPipelines.GitHubWorkflow(app, "GithubPipeline",
>   worfklow_name="CI",
>   job_settings= GithubPipelines.JobSettings("if", "github.organization == 'my_org'"), # i haven't thought through the API but it would be set here
> )
> ```
I think this kind of implementation makes sense (basically exposing `jobs.<job_id>.<XYZ>` properties within `JobSettings`). It would also be worth adding that `job_settings` argument to the `add_stage` method as well (or I suppose any method that results in a new Job being added to the workflow file). 

I'm thinking in particular of pipelines that behave differently depending on GH context (e.g. Don't run the deploy job if the workflow is running against a pull request)

**Comment by kaizencc** [comment]
Opened #293 to track escape hatching
