### ISSUE TITLE
Golang support

### ISSUE THREAD

**Issue by karl-dau** [cdklabs/cdk-pipelines-github#256]
Any plans for Golang support? I assume the Go code can be generated like most of the other CDK things?

**Comment by kaizencc** [comment]
Yes, since Go support is GA then this should be fairly easy to do. Lets see if I can set that up in a bit.

**Comment by karl-dau** [comment]
@kaizencc Thanks, any progress with this?

**Comment by kaizencc** [comment]
@karl-dau, #484 should have added go support for free :).

The go bindings live [here](https://github.com/cdklabs/cdk-pipelines-github-go). Let me know if you get the chance to try them out!

**Comment by karl-dau** [comment]
@kaizencc Sorry, only getting around to this now; the bindings don't seem to be at that address?

**Comment by karl-dau** [comment]
@kaizencc has the Go port been abandoned?
