### ISSUE TITLE
Usage of `Job` with GitHubWorkflow for Step Outputs

### ISSUE THREAD

**Issue by joelhamiltondev** [cdklabs/cdk-pipelines-github#346]
Is there any way we can use Jobs instead of JobSteps when specifying the steps of a GitHubWorkflow?

Struggling to get the steps in my workflow to output specific values. Currently passing in some JobSteps as pre-build steps.

How can we set the steps in a workflow to use Jobs rather?

**Comment by joelhamiltondev** [comment]
Hi Kaizen, a bit difficult to share code as a lot of it is private and is being used on client work.

Essentially, I cannot find any code examples of where the `Job` struct can be used in a workflow. If you know of any, could you please link them to me?

Also: We are using the `GitHubWorkflow` construct to create a workflow which runs whenever we create a PR. We use the `preBuildSteps` field to set which steps run in the workflow. This array only takes in objects of type `JobStep`, not `Job`. 

My question is essentially: how can we use the `Job` struct with the GitHubWorkflow construct?

**Comment by kaizencc** [comment]
The answer to your question is you can't, really. The `Job` construct is an implementation detail that is not exposed to the user. We expose `steps` to the user because that's universal for all kids of pipelines -- it just so happens that the pipeline in this library is backed by GitHub Workflows and has a concept of a Job.

My follow up question: why do you need to access the underlying `Job` construct? If you need to change some configuration for it, perhaps the newly added [escape hatches](https://github.com/cdklabs/cdk-pipelines-github#escape-hatches) might be helpful here.

**Comment by kaizencc** [comment]
If there's a specific feature in mind that you think this library should support, like accessing a particular property of a job, let me know and I'm happy to see if that makes sense.

**Comment by joelhamiltondev** [comment]
Hi @kaizencc , thanks for your response.

What we're trying to do is set a JobStep to have particular outputs - (e.g. similar to the field `outputs` in a regular yaml-defined github action)

**Comment by kaizencc** [comment]
Without code it's a bit difficult to guide you. I suppose you're asking for something like `pipeline.prependJob()` or something to allow any sort of jobs into the pipeline. 

I'm curious where you plan to consume the `output` of a job prior to build. My main problem with supplying APIs to change whatever you want in the workflow is that they will be used to create impossibly complex (and invalid) configurations, which we "support" by having APIs for them. Right now, you can do whatever you want with escape hatches, but they are more clearly marked "be careful what you wish for".

**Comment by joelhamiltondev** [comment]
Understood - we will likely use escape hatches for what we require.

usage for `output` prior to build:
- step 1: performs some action
- step 2: does some other action
- step 3: conditionally performs an action, dependent on the result of step 1 and step 2

How could we reference the outputs of step 1 and 2 in the condition for step 3?
