### ISSUE TITLE
diffProtection can't be disabled with `--context` option

### ISSUE THREAD

**Issue by christophgysin** [cdklabs/cdk-pipelines-github#381]
AFAIK it is not possible to pass typed context values using `--context`. See also https://github.com/aws/aws-cdk/issues/2204.

This makes it impossible to get past the check at https://github.com/cdklabs/cdk-pipelines-github/blob/main/src/pipeline.ts#L300-L301:
```ts
    const diffProtection = this.node.tryGetContext('cdk-pipelines-github:diffProtection') ?? true;
    if (diffProtection && process.env.GITHUB_WORKFLOW === this.workflowName) {
```
I suggest to also allow string values (`"false"`) to disable the check.

**Comment by kaizencc** [comment]
Sure. If you submit this with a test I'll be happy to accept it. Otherwise, there are other ways of turning it off.

**Comment by christophgysin** [comment]
@kaizencc Sure, please check my proposed fix in PR https://github.com/cdklabs/cdk-pipelines-github/pull/385
