### ISSUE TITLE
GitHub error: `Node.js 12 actions are deprecated`

### ISSUE THREAD

**Issue by giseburt** [cdklabs/cdk-pipelines-github#393]
> For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

These versions are hardcoded into `pipeline.ts` and cause the pipelines made to fail:
- `actions/checkout`
- `actions/setup-node`
- `actions/upload-artifact`
- `actions/download-artifact`
- `aws-actions/aws-cloudformation-github-deploy`

That last one, `aws-actions/aws-cloudformation-github-deploy`, is in a repo that's archived (last release: August 2020). I couldn't find an obvious replacement, so I'm not sure what the solution to that one should be.

`aws-actions/configure-aws-credentials@v1` appears to be fine, as it updated to node16 without a major version change of the action.

**Comment by giseburt** [comment]
I don't believe `aws-actions/aws-cloudformation-github-deploy` is necessary, considering we have `npx cdk deploy` readily available.

**Comment by kaizencc** [comment]
Oh no. Does this mean that this library has been unusable since September 27? In the short run, I think I'll just update the action versions manually. In the long run, we need to fix this hardcoding problem...

**Comment by kaizencc** [comment]
Ok it seems like the pipeline still succeeds but we get a ton of warning messages telling us that the sky will fall soon (#403 as well). We'll need to do something about this asap.
