### ISSUE TITLE
Older GitHub actions and dependabot

### ISSUE THREAD

**Issue by webjunkie** [cdklabs/cdk-pipelines-github#395]
Problem:

I already have dependabot configured to update GitHub actions in my repository. I then add a CDK pipeline workflow. I will receive updates from dependabot to change the pipeline workflow file. If I merge the update, the workflow will no longer run due to the diff check. `upload-artifact` is such an action for example.

Not sure what could be done here, as updates to actions should probably also be tested somehow and not just included into the generated workflow.

**Comment by giseburt** [comment]
This is somewhat related to the core issue of #393 - specifically, managing the versions of actions.

**Comment by kaizencc** [comment]
Lots of conversation on #393, and this is something I'm looking to rectify soon. Closing this issue in favor of tracking everything in one spot.
