### ISSUE TITLE
Allow access to `permissions` property of GitHubActionStep's in pre/post

### ISSUE THREAD

**Issue by jsadoski-rockhall** [cdklabs/cdk-pipelines-github#731]
#304 is a great feature, however, it doesn't not provide a surface to control the `permissions` property emitted for the job. This means that the job emitted cannot be provided with the `id-token: write` permission and cannot authenticate with AWS using the GitHub identity provider.

Either access to the `permissions` property of the `GitHubActionStep` or the ability to pass `id-token: write` as a boolean would make `GitHubActionStep`'s much more useful in pre/post deploy steps.

Taking a look over #304, I think the change should be fairly trivial? Provided I have time, I may be able to open a PR.

**Comment by kaizencc** [comment]
Please open a PR! This library is basically exclusively open source contributions at this point. I think access to `permissions` makes the most sense, but that's just my initial opinion.
