### ISSUE TITLE
Upgrade aws-actions/configure-aws-credentials to v4

### ISSUE THREAD

**Issue by jsadoski-rockhall** [cdklabs/cdk-pipelines-github#742]
The current `aws-actions/configure-aws-credentials` is several versions out of date. The latest version is [aws-actions/configure-aws-credentials@v4](https://github.com/aws-actions/configure-aws-credentials/releases/tag/v4.0.1). Changing this line should do it:

https://github.com/cdklabs/cdk-pipelines-github/blob/bc87ea55fae5189974f74cca3a4e4c14fa3102ea/src/private/aws-credentials.ts#L91

Here's the current warning in the pipeline I'm getting:

```
(node:1674) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
```

Happy to open a PR. Thank you for this awesome project!

**Comment by kaizencc** [comment]
Please open a PR and then ping me! I will be happy to get this update in. Just gotta make sure there are no weird breakages. We originally had to use `v1-node16` because of some reason... there may be some breakages between v1 and v4 that we have to figure out. Fingers crossed that there are not...
