### ISSUE TITLE
Add support for aws-cn partition

### ISSUE THREAD

**Issue by mbergkvist** [cdklabs/cdk-pipelines-github#820]
I'm working on support for deploying to aws-cn, the wip-pr is here: https://github.com/mbsoftworks/cdk-pipelines-github/pull/1

It works for my use case (though there might be more required changes for other use cases) but I need some help to remove the hard-coded `aws-cn` and `.amazonaws.com.cn` changes (https://github.com/mbsoftworks/cdk-pipelines-github/pull/1/commits/d2ed0187a543b75d5a70408e7a71139eb44c10e9). Any suggestion on what needs to be done to fix those?

**Comment by kaizencc** [comment]
@mbergkvist -- the ask is to remove the hardcoded `aws` partition to instead be possibly `aws-cn` based on some information right? I am open to it... we can either have it be a well-known environment variable if you want to modify the partition, or we can somehow get the info from the stack environment. I'm happy to start with env variable because that sounds easier, at the expense of some user experience, but at least it's possible :).

This module isn't really maintained for new feature requests. I am happy to review any community contributions on this, but do not have time to do so on my own.

**Comment by mbergkvist** [comment]
@kaizencc 

> I am happy to review any community contributions on this, but do not have time to do so on my own.

I'm happy to work on this, but I'd need some guidance. I'm not too familiar with the inner workings of the CDK framework.

> we can either have it be a well-known environment variable if you want to modify the partition, or we can somehow get the info from the stack environment

An environment variable could work, but as you say, it comes with a cost for the user experience. The alternative is to get the infomration from the `StackDeployment` parameter, but unfortunately it doesn't carry the partition (in the long-term, should there be a PR in aws-cdk-lib pipelines?), but perhaps we can draw some conclusion based on the region? E.g. if the region begins with `cn-` then we set the partition to `aws-cn`.

The second part in my PR, the replacement of `.amazonaws.com` with `.amazonaws.com.cn`, is an hack I'm not particular proud of and I think it should be changed upstream so correct URL's are created from the start for the assets. Nevertheless, we can start with adding the change behind the same region logic as above?

I think the changes in `src/oidc-provider.ts` is legit, should I create a separate PR for those?

**Comment by mbergkvist** [comment]
@kaizencc I created a separate PR (#868) for replacing the hard coded aws partition in `GitHubActionRole` with AWS:Partition. I think that can be merged without the other changes necessary for aws-cn support.

**Comment by mbergkvist** [comment]
@kaizencc I went with the well-known environment variable to do the required changes in the pipeline, #895. A proper solution would probably be to make sure the partition is known in the pipeline, and also that the partition is known when the template is created, but as a temporary work-around, this has worked quite well for us.
